USE [master]
GO

/****** Object:  Database [cab_booking]    Script Date: 25-07-2017 02:27:35 ******/
CREATE DATABASE [cab_booking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cab_booking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\cab_booking.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'cab_booking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\cab_booking_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [cab_booking] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cab_booking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cab_booking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cab_booking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cab_booking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cab_booking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cab_booking] SET ARITHABORT OFF 
GO

ALTER DATABASE [cab_booking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cab_booking] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [cab_booking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cab_booking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cab_booking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cab_booking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cab_booking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cab_booking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cab_booking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cab_booking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cab_booking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cab_booking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cab_booking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cab_booking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cab_booking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cab_booking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cab_booking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cab_booking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cab_booking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [cab_booking] SET  MULTI_USER 
GO

ALTER DATABASE [cab_booking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cab_booking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cab_booking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cab_booking] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [cab_booking] SET  READ_WRITE 
GO


